FROM adoptopenjdk/openjdk8:alpine-jre
ADD springboot-crud-application-demo/target/crudapplication-0.0.1-SNAPSHOT.jar crudapplication-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","crudapplication-0.0.1-SNAPSHOT.jar"]