pipeline {
    agent any
    environment {
        KUBECONFIG = credentials('kubeconfig') 
        IMAGE_TAG = 'khaoulaout/my-back-app:jma-4.0 .' 
        NAMESPACE = 'default' 
    }


    stages {
        stage('Build') {
            steps {
                dir('springboot-crud-application-demo') { 
                    sh 'docker build -t khaoulaout/my-back-app:jma-4.0 .'
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                    sh "echo $PASS | docker login -u $USER --password-stdin"
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh 'docker push khaoulaout/my-back-app:jma-4.0'
            }
        }

         stage('Deploy') {
            steps {
                script {
                    // Configure kubectl with the provided kubeconfig
                    withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                        sh "kubectl --kubeconfig=$KUBECONFIG apply -f springboot-angular12-mysql-docker/deployment.yml --record"
                        //sh "kubectl --kubeconfig=$KUBECONFIG set image deployment/your-app-deployment your-app-container=$IMAGE_TAG"
                    }
                }
            }
        }
    }
}
