pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('springboot-crud-application-demo') {
                    sh 'docker build -t khaoulaout/my-back-app:jma-1.0 .'
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                    sh "echo $PASS | docker login -u $USER --password-stdin"
                }
            }


        stage('Push to Docker Hub') {
            steps {
                sh 'docker push khaoulaout/my-back-app:jma-1.0'
            }
        }

        
    }
}
